name: 'coalesce_22_inherited_project_refactoring_workshop'
version: '1.0.0'
config-version: 2

profile: 'bigquery_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  coalesce_22_inherited_project_refactoring_workshop:
    marts:
      materialized: table

  - name: stg_tpch__part_suppliers
    columns:
      - name: available_qty
        tests:
          - not_null:
              config:
                severity: error
                error_if: ">35"
                warn_if: ">0"
                where: "supply_cost > 0"
